version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  cst: cst/framework@dev:phase_1

workflows:
  version: 2
  yeet-le-jobs:
    jobs:
      - cst/enforce-gem-version-bump
      - cst/rspec-ruby:
          rspec-system-args: "SIMPLE_COV_RUN=true"
          cc-report-collect-ruby: "2.7.5"
          matrix:
            parameters:
              ruby-version: ["2.7.5" , "3.0.0", "3.0.3"]
            alias: required-matrix-tests
          name: test-ruby<< matrix.ruby-version >>
      - cst/publish-gem:
          publish-git: true
          publish-default-gem: true
          requires:
            - required-matrix-tests
            - cst/enforce-gem-version-bump
          filters:
            branches:
              only:
                - main
